spring:
  application:
    name: fair-donation-point-poc-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
